### ISSUE TITLE
Includes for inherited content are not added to the current page

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#10]
When content is inherited through the use of `interit="true"`, its includes are not added to the output of the `HTMLHeader` tag.

The problem stems from the fact that so far, a page does not know about its composers, which means that the logic to determine inherited content can't be leveraged by the header tag. Most certainly, there needs to be a registration of the composers, likely done by the precompiler.

**Comment by myniva** [comment]
Seems to be a major bug because the "includes-feature" is not reliable enough without having this fixed.

**Comment by ghost** [comment]
A potential solution to this would be to cache the output of the body and only send it back once everything has been processed and thereby the full list of includes has been determined.

**Comment by ghost** [comment]
The response is now cached in WebloungeResponseImpl and headers are added after the fact but before the response is sent back.
