### ISSUE TITLE
Action-Response inherits Last-Modified date from underlaying page by mistake

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#110]
Therefore a Request with `If-Modified-Since`allways returns `304 NOT_MODIFIED` even if the response content changed.

**Comment by ghost** [comment]
The problem was that EHCache was returning entries that had been expired but not evicted from the cache. Reading up on it reveals that this is not unlikely to happen, so code has been added to ignore and delete those elements from the cache when encountered.
