### ISSUE TITLE
Search request handler: AND as default conjunction

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#116]
If the search query contains more then one term (e.g. **basil brunner**), the search request handler returns pages which contain either **basil** `OR` **brunner**. IMHO most users would expect to search for **basil** `AND` **brunner**.

**Comment by ghost** [comment]
Basil, the query should also return pages that contain both terms, and even rank them higher. Is that not the case for you?

**Comment by betsim** [comment]
+1 for Basils suggestion. google also uses `AND` as default conjunction

**Comment by myniva** [comment]
As yakarij commented, the search request handlers ranks pages which contain **all** terms higher than pages which contain only some/one of them. This solution works for me.
