### ISSUE TITLE
CacheTest should check, if cache is enabled

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#119]
At the moment, the CacheTest (in weblounge-test) assumes that the response cache is always enabled. Send a request to the cache endpoint to check if the cache is enabled.

**Comment by ghost** [comment]
Introduced a new request header X-Cache-Debug to indicate to the cache whether to send the cache key as part of the header or not. This key is now used to test whether the cache is online or not. Tests are not succeeding regardless of the cache status.
