### ISSUE TITLE
Action recheck time should never be bigger than valid time

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#123]
Assume an action with the following configuration:

´
<action id="LivetickerAjaxAction">
   <name>LivetickerAjaxAction</name>
   <class>ch.swissunihockey.weblounge.module.league.result.LivetickerAjaxAction</class>
   <mountpoint>/spielbetrieb/liveticker/ajax</mountpoint>
   <valid>1M</valid>
 </action>
`

In this case, action.getRecheckTime() will return '1h', the default recheck time set in `GeneralComposeable`.

IMO a action's recheck value should never be bigger than it's valid time. This should be checked each time the recheck time or the valid time is set to a new value.

**Comment by ghost** [comment]
Basil, your assumption is correct. I adusted the implementation of `getClientRecheckTime` to return the minimum of the recheck time and the valid time.
