### ISSUE TITLE
Images-dialog disappears

### ISSUE THREAD

**Issue by betsim** [digitalroastery/weblounge#145]
When inserting an image-element outside the viewport, the dialog does not reappear after selecting the image. It helps to change the size of the browser-viewport to make the dialog reappear.

**Comment by myniva** [comment]
I cannot reproduce this bug with Safari 6.0.1 nor with Firefox 16 - or maybe I'm not doing exactly the same you were doing. Could you provide a step-by-step instruction?

**Comment by myniva** [comment]
I think, we definitely should fix this bug, but for me it's not a blocker. We have to make sure that we inform the system users though.

**Comment by betsim** [comment]
I agree! I could produce a little screencast. Would be nice to have a website for weblounge release notes...
