### ISSUE TITLE
Last-Modified value of styled image does not equal its generation time

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#162]
If i request a image styled by an image style (e.g. `http://www.swissunihockey.ch/weblounge-images/19bc0168-7810-4d15-b01e-7bc30cffc8a1/de?style=clublogo`) the Last Modified header is `Wed, 27 Sep 2006 15:57:23 GMT`(for my example) which cannot be the date the image was styled/scaled aka last modified.

The `Last Modified` header should represent the date the styled image was last written to disk.

**Comment by ghost** [comment]
Currently, the modified date equals the modification date of the original image. But you are right, given that image style definitions may change, it should definitely be the scaled image's creation date.
