### ISSUE TITLE
Wrong warning "Invalid fields" in pagelet editor

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#216]
If I open an editor, there's always a warning indicating that there are wrong fields, even if I entered nothing or all the fields.

**Comment by betsim** [comment]
The validation has to be reseted after closing a dialog (or bevore open a dialog).

**Comment by myniva** [comment]
I think, the root cause did come with this commit: 588c7a19ca1cf27fb595312f4fdb6b056a08cbb6

**Comment by myniva** [comment]
It overrides the css rule `display: hidden` defined in class `.hidden`

**Comment by myniva** [comment]
@betsim, could you please comment, why `display: inline-block` is needed there?
