### ISSUE TITLE
Endpoints published for all sites

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#243]
If one site publishes an endpoint, it's accessible via all available pages. Example: Site `demo` with url `http://demo` publishes an endpoint mounted to `/myendpoint`. There's an other site in the system called `test` with url `http://test`. The endpoint is available via `http://demo/myendpoint` & `http://test/myendpoint`

**Comment by ghost** [comment]
Another problem is that there will be name clashes when two sites try to register an endpoint on the same path.
