### ISSUE TITLE
SearchQuery has function to set a date range only with an end date

### ISSUE THREAD

**Issue by Buttyx** [digitalroastery/weblounge#252]
It should be possible to create a range for the creation/modification dates only with the end date.

**Comment by ghost** [comment]
Xavier, simply use

```
      q.withCreationDateBetween(new Date(0));
      q.and(creatorEndDate);
```

This will set the start date of the range query to the earliest date/time possible.

Tobias

**Comment by Buttyx** [comment]
Thanks, I was already using it. I just thought it could be useful to add a query method to create a range only with the end date.
