### ISSUE TITLE
ContentIteratorTag does not work for editor pagelets

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#34]
The `ContentEditorTag` makes a call to `if (RequestUtils.isMockRequest(request))` since rendering without page data leads to an error. Unfortunately, all requests made to render the editor pagelets are MockRequest instances and therefore, the tag is not working inside editor pagelets. This behavior may occur in other tags.

**Comment by ghost** [comment]
Implemented a precompile request in order to distinguish between this kind of request vs. mock requests
